In [2]:
import pandas as pd

# Tạo Series về diện tích
area_dict = {
    'Hà Nội': 3358.9,
    'Quảng Ninh': 6177.7,
    'Nam Định': 1668.0,
    'Đà Nẵng': 1284.9,
    'TP.Hồ Chí Minh': 2061.0
}
area = pd.Series(area_dict)

# Tạo Series về dân số
population_dict = {
    'Hà Nội': 8250000,
    'Quảng Ninh': 1400000,
    'Nam Định': 1800000,
    'Đà Nẵng': 1200000,
    'TP.Hồ Chí Minh': 9100000
}
population = pd.Series(population_dict)

# Tạo DataFrame
VietNam = pd.DataFrame({'Dân số': population, 'Diện tích': area})
print(VietNam)

                 Dân số  Diện tích
Hà Nội          8250000     3358.9
Quảng Ninh      1400000     6177.7
Nam Định        1800000     1668.0
Đà Nẵng         1200000     1284.9
TP.Hồ Chí Minh  9100000     2061.0

In [3]:
VietNam['Dân số']

Hà Nội            8250000
Quảng Ninh        1400000
Nam Định          1800000
Đà Nẵng           1200000
TP.Hồ Chí Minh    9100000
Name: Dân số, dtype: int64

In [4]:
print('Dân số thủ đô Hà Nội:',VietNam['Dân số']['Hà Nội']) 
print('Dân số thủ đô Hà Nội:',VietNam['Dân số'][0])

Dân số thủ đô Hà Nội: 8250000
Dân số thủ đô Hà Nội: 8250000

C:\Users\Admin\AppData\Local\Temp\ipykernel_17812\2035524032.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print('Dân số thủ đô Hà Nội:',VietNam['Dân số'][0])

In [5]:
#Tạo DataFrame từ một Series 
pd.DataFrame(population, columns=['Dân số'])

                 Dân số
Hà Nội          8250000
Quảng Ninh      1400000
Nam Định        1800000
Đà Nẵng         1200000
TP.Hồ Chí Minh  9100000

In [6]:
data = [{'a':i,'b':2*i} 
for i in range(3)] 
data

[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 4}]

In [7]:
pd.DataFrame(data)

   a  b
0  0  0
1  1  2
2  2  4

In [8]:

pd.DataFrame([{'a':1,'b':2},{'b':3,'c': 'KHDL'}])

     a  b     c
0  1.0  2   NaN
1  NaN  3  KHDL

In [9]:
VietNam=pd.DataFrame({'Dân số':population,'Diện tích':area})

In [10]:
import numpy as np 
arr=np.random.rand(3,2) 
arr

array([[0.03315042, 0.07762185],
       [0.1187762 , 0.86971012],
       [0.16691634, 0.36582066]])

In [ ]:
pd.DataFrame(arr,columns=['foo','bar'],index=['a','b','c'])

        foo       bar
a  0.033150  0.077622
b  0.118776  0.869710
c  0.166916  0.365821

:

In [ ]:

print(data.dtype)