In [1]:
import pandas as pd 
population = pd.Series({'Hà Nội':8330830, 
                        'Quảng Ninh':1358490, 
                        'Nam Định': 1771000, 
                        'Đà Nẵng':1191381, 
                        'TP.Hồ Chí Minh':9411805}) 
area=pd.Series({'Hà Nội':3358.9, 
                 'Quảng Ninh':6177.7, 
                 'Nam Định': 1668.0, 
                 'Đà Nẵng':1284.9, 
                 'TP.Hồ Chí Minh':2061.0}) 
data = pd.DataFrame({'Dân số':population, 'Diện tích':area}) 
data

                 Dân số  Diện tích
Hà Nội          8330830     3358.9
Quảng Ninh      1358490     6177.7
Nam Định        1771000     1668.0
Đà Nẵng         1191381     1284.9
TP.Hồ Chí Minh  9411805     2061.0

In [2]:
arr_data = data.values # Lấy mảng dữ liệu gốc từ DataFrame 
print(arr_data)

[[8.330830e+06 3.358900e+03]
 [1.358490e+06 6.177700e+03]
 [1.771000e+06 1.668000e+03]
 [1.191381e+06 1.284900e+03]
 [9.411805e+06 2.061000e+03]]

In [3]:
data.T

              Hà Nội  Quảng Ninh   Nam Định    Đà Nẵng  TP.Hồ Chí Minh
Dân số     8330830.0   1358490.0  1771000.0  1191381.0       9411805.0
Diện tích     3358.9      6177.7     1668.0     1284.9          2061.0

In [ ]:
print("Cách 1, sử dụng chuyển vị:", data.T.values[1]) 
print("Cách 2, sử dụng chỉ mục(index): ", data['Diện tích'].values)

Cách 1, sử dụng chuyển vị: [3358.9 6177.7 1668.  1284.9 2061. ]
Cách 2, sử dụng chỉ mục(index):  [3358.9 6177.7 1668.  1284.9 2061. ]

: