In [1]:
import pandas as pd 
population = pd.Series({'Hà Nội':8330830, 
                        'Quảng Ninh':1358490, 
                        'Nam Định': 1771000, 
                        'Đà Nẵng':1191381, 
                        'TP.Hồ Chí Minh':9411805}) 
area=pd.Series({'Hà Nội':3358.9, 
                 'Quảng Ninh':6177.7, 
                 'Nam Định': 1668.0, 
                 'Đà Nẵng':1284.9, 
                 'TP.Hồ Chí Minh':2061.0}) 
data = pd.DataFrame({'Dân số':population, 'Diện tích':area}) 
data

                 Dân số  Diện tích
Hà Nội          8330830     3358.9
Quảng Ninh      1358490     6177.7
Nam Định        1771000     1668.0
Đà Nẵng         1191381     1284.9
TP.Hồ Chí Minh  9411805     2061.0

In [2]:
data['Dân số']   #Lấy cột 'Dân số'

Hà Nội            8330830
Quảng Ninh        1358490
Nam Định          1771000
Đà Nẵng           1191381
TP.Hồ Chí Minh    9411805
Name: Dân số, dtype: int64

In [3]:
#’tạo cột mới ‘popolution’ từ cột ‘Dân số’  
data['population'] = data['Dân số']   
print(data)

                 Dân số  Diện tích  population
Hà Nội          8330830     3358.9     8330830
Quảng Ninh      1358490     6177.7     1358490
Nam Định        1771000     1668.0     1771000
Đà Nẵng         1191381     1284.9     1191381
TP.Hồ Chí Minh  9411805     2061.0     9411805

In [4]:
data.population

Hà Nội            8330830
Quảng Ninh        1358490
Nam Định          1771000
Đà Nẵng           1191381
TP.Hồ Chí Minh    9411805
Name: population, dtype: int64

In [ ]:
data['Mật độ']=data['Dân số']/data['Diện tích'] 
 
data

                 Dân số  Diện tích  population       Mật độ
Hà Nội          8330830     3358.9     8330830  2480.225669
Quảng Ninh      1358490     6177.7     1358490   219.902229
Nam Định        1771000     1668.0     1771000  1061.750600
Đà Nẵng         1191381     1284.9     1191381   927.216904
TP.Hồ Chí Minh  9411805     2061.0     9411805  4566.620573

: